### ISSUE TITLE
Any plan for change/remove?

### ISSUE THREAD

**Issue by casouri** [tslilc/siege-mode#2]
This is cool! Is there any plan for support of changing and removing pairs by regex?

**Comment by tslilc** [comment]
Thanks for the suggestion. I hadn't originally planned this for siege mode. I'm not convinced it really fits the purview of mode, but I would certainly be open to contributions along this avenue. The way things are currently written (that is, poorly) may prove to be something of an obstruction to this. I'd be happy to discuss details if you were looking to try your hand at it.

**Comment by casouri** [comment]
I actually made something similar based on your idea. You can have a look at isolate.el.

I hope you don’t feel offended because I didn’t choose to build on yours. Sorry : (

**Comment by tslilc** [comment]
Not at all, very nice job on `isolate.el` and thanks for the credit! I'm really happy that you found the idea useful!

`isolate.el ` looks very mature and well thought out, it would take a significant amount of work to make `siege-mode` as feature complete, so in the future i may just contribute there directly instead.
